
import { VoiceArtist, ArtistCategory, Emotion } from './types';

// Helper to generate avatars
const getAvatar = (id: string, gender: 'Male' | 'Female') => 
  `https://picsum.photos/seed/${id}-${gender}/200/200`;

// Base voices available in Gemini API
// Male: Puck, Charon, Fenrir
// Female: Kore, Zephyr
const BASE_VOICES = ['Puck', 'Charon', 'Kore', 'Fenrir', 'Zephyr'] as const;

export const SUPPORTED_LANGUAGES = [
  "English", "Spanish", "French", "German", "Japanese", "Mandarin Chinese", "Hindi", 
  "Portuguese", "Russian", "Italian", "Korean", "Dutch", "Turkish", "Arabic", 
  "Polish", "Swedish", "Indonesian", "Vietnamese", "Thai", "Greek", "Czech", 
  "Danish", "Finnish", "Norwegian", "Hungarian", "Romanian", "Ukrainian", "Hebrew", 
  "Malay", "Tagalog", "Bengali", "Punjabi", "Tamil", "Telugu", "Marathi"
].sort();

export const SPEEDS = ['Very Slow', 'Slow', 'Normal', 'Fast', 'Very Fast'];

export const RESEARCH_CATEGORIES = [
  "AI & Technology", 
  "Finance & Investing", 
  "Gaming", 
  "History", 
  "Medical & Health", 
  "Comedy", 
  "Entertainment", 
  "Science", 
  "Personal Development", 
  "Travel", 
  "Food & Cooking", 
  "True Crime", 
  "DIY & Crafts", 
  "News & Politics", 
  "Sports", 
  "Automotive",
  "Fashion & Beauty"
].sort();

// Generating Artists
// CRITICAL: Ensure Gender matches Base Voice.
// Male: Fenrir, Puck, Charon
// Female: Kore, Zephyr
export const ARTISTS: VoiceArtist[] = [
  // --- POPULAR / PREMIUM ---
  { id: 'pop-m-1', name: 'Adam', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Deep, rich, American narrator. The gold standard.', avatarUrl: getAvatar('pop-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'pop-m-2', name: 'Antoni', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Fenrir', description: 'Well-rounded, polite, and balanced.', avatarUrl: getAvatar('pop-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'pop-m-3', name: 'Josh', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Deep, emotional, resonance suitable for audiobooks.', avatarUrl: getAvatar('pop-m-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'pop-m-4', name: 'Arnold', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Charon', description: 'Distinctive, crisp, and slightly older tone.', avatarUrl: getAvatar('pop-m-4', 'Male'), language: 'English', accent: 'American' },
  { id: 'pop-m-5', name: 'Wayne', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Corporate, serious, and direct.', avatarUrl: getAvatar('pop-m-5', 'Male'), language: 'English', accent: 'American' },
  
  { id: 'pop-f-1', name: 'Aoede', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Muse-like, poetic, and incredibly expressive.', avatarUrl: getAvatar('pop-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'pop-f-2', name: 'Rachel', gender: 'Female', category: ArtistCategory.Explanatory, baseVoice: 'Kore', description: 'Clear, narrative, American standard.', avatarUrl: getAvatar('pop-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'pop-f-3', name: 'Bella', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Zephyr', description: 'Soft, delicate, and very intimate.', avatarUrl: getAvatar('pop-f-3', 'Female'), language: 'English', accent: 'American' },
  { id: 'pop-f-4', name: 'Elli', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Zephyr', description: 'Young, bright, and enthusiastic.', avatarUrl: getAvatar('pop-f-4', 'Female'), language: 'English', accent: 'American' },
  { id: 'pop-f-5', name: 'Nicole', gender: 'Female', category: ArtistCategory.Educational, baseVoice: 'Kore', description: 'Soothing professional, perfect for learning.', avatarUrl: getAvatar('pop-f-5', 'Female'), language: 'English', accent: 'American' },

  // --- NEW ADDITIONS: 100 ENGLISH ARTISTS (50 Male, 50 Female) ---
  
  // -- MALE BRITISH (25) --
  { id: 'uk-m-1', name: 'Arthur Kingsman', gender: 'Male', category: ArtistCategory.HistoricalNarrator, baseVoice: 'Fenrir', description: 'Distinguished British RP accent, ideal for history.', avatarUrl: getAvatar('uk-m-1', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-2', name: 'Oliver Sterling', gender: 'Male', category: ArtistCategory.Professional, baseVoice: 'Puck', description: 'Crisp London business tone, very articulate.', avatarUrl: getAvatar('uk-m-2', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-3', name: 'Harry Potter-ish', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Puck', description: 'Youthful British storyteller, magical and bright.', avatarUrl: getAvatar('uk-m-3', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-4', name: 'George Windsor', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Deep, aristocratic British calm.', avatarUrl: getAvatar('uk-m-4', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-5', name: 'Liam Mancunian', gender: 'Male', category: ArtistCategory.Energetic, baseVoice: 'Puck', description: 'Friendly Northern England accent, down to earth.', avatarUrl: getAvatar('uk-m-5', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-6', name: 'Benedict B.', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Fenrir', description: 'Low, resonant, detective style British voice.', avatarUrl: getAvatar('uk-m-6', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-7', name: 'Noah Oxford', gender: 'Male', category: ArtistCategory.Educational, baseVoice: 'Puck', description: 'Intellectual, academic Oxford accent.', avatarUrl: getAvatar('uk-m-7', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-8', name: 'Sir James', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Charon', description: 'Elderly British historian tone.', avatarUrl: getAvatar('uk-m-8', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-9', name: 'Alfie Lad', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'Cheeky, high energy London street style.', avatarUrl: getAvatar('uk-m-9', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-10', name: 'Dr. Watson', gender: 'Male', category: ArtistCategory.Medical, baseVoice: 'Fenrir', description: 'Clinical, precise British medical professional.', avatarUrl: getAvatar('uk-m-10', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-11', name: 'Ian Scott', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Charon', description: 'Warm Scottish burr, cozy and inviting.', avatarUrl: getAvatar('uk-m-11', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-12', name: 'William Bard', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Theatrical Shakespearean delivery.', avatarUrl: getAvatar('uk-m-12', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-13', name: 'Charlie News', gender: 'Male', category: ArtistCategory.News, baseVoice: 'Puck', description: 'BBC style news anchor, neutral and serious.', avatarUrl: getAvatar('uk-m-13', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-14', name: 'Thomas Tank', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Puck', description: 'Playful, animated British character.', avatarUrl: getAvatar('uk-m-14', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-15', name: 'Edward Gloom', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Fenrir', description: 'Dark, gothic British horror narrator.', avatarUrl: getAvatar('uk-m-15', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-16', name: 'Freddie Fun', gender: 'Male', category: ArtistCategory.Energetic, baseVoice: 'Puck', description: 'Upbeat British gaming YouTuber vibe.', avatarUrl: getAvatar('uk-m-16', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-17', name: 'Rupert Rich', gender: 'Male', category: ArtistCategory.Professional, baseVoice: 'Charon', description: 'Wealthy, upper-class British accent.', avatarUrl: getAvatar('uk-m-17', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-18', name: 'Nigel Nature', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Nature documentary whisperer style.', avatarUrl: getAvatar('uk-m-18', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-19', name: 'Simon Says', gender: 'Male', category: ArtistCategory.Explanatory, baseVoice: 'Puck', description: 'Clear, instructional British tech voice.', avatarUrl: getAvatar('uk-m-19', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-20', name: 'Gerry Gravel', gender: 'Male', category: ArtistCategory.ASMR, baseVoice: 'Charon', description: 'Deep vocal fry, British accent ASMR.', avatarUrl: getAvatar('uk-m-20', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-21', name: 'Leo London', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'Modern, urban London accent.', avatarUrl: getAvatar('uk-m-21', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-22', name: 'Henry History', gender: 'Male', category: ArtistCategory.HistoricalNarrator, baseVoice: 'Fenrir', description: 'Grand, epic British history narrator.', avatarUrl: getAvatar('uk-m-22', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-23', name: 'Jack Joker', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Puck', description: 'Sarcastic, dry British wit.', avatarUrl: getAvatar('uk-m-23', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-24', name: 'Oscar Owl', gender: 'Male', category: ArtistCategory.Educational, baseVoice: 'Charon', description: 'Wise, older British professor.', avatarUrl: getAvatar('uk-m-24', 'Male'), language: 'English', accent: 'British' },
  { id: 'uk-m-25', name: 'Felix Fast', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Rapid fire British sports commentary.', avatarUrl: getAvatar('uk-m-25', 'Male'), language: 'English', accent: 'British' },

  // -- MALE AMERICAN (25) --
  { id: 'us-m-1', name: 'Mike Broadcast', gender: 'Male', category: ArtistCategory.News, baseVoice: 'Fenrir', description: 'Standard American trusted news anchor.', avatarUrl: getAvatar('us-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-2', name: 'Steve Sales', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'High energy American car commercial voice.', avatarUrl: getAvatar('us-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-3', name: 'David Doc', gender: 'Male', category: ArtistCategory.Medical, baseVoice: 'Charon', description: 'Calm, reassuring American doctor.', avatarUrl: getAvatar('us-m-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-4', name: 'Chris Coach', gender: 'Male', category: ArtistCategory.Energetic, baseVoice: 'Fenrir', description: 'Motivational speaker, loud and clear.', avatarUrl: getAvatar('us-m-4', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-5', name: 'Ethan Explains', gender: 'Male', category: ArtistCategory.Explanatory, baseVoice: 'Puck', description: 'Friendly, tech-bro explainer voice.', avatarUrl: getAvatar('us-m-5', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-6', name: 'Sam Story', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Charon', description: 'Campfire storyteller, warm and raspy.', avatarUrl: getAvatar('us-m-6', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-7', name: 'Ryan Relax', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Meditation guide, deep American voice.', avatarUrl: getAvatar('us-m-7', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-8', name: 'Jason Justice', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Fenrir', description: 'Movie trailer guy style.', avatarUrl: getAvatar('us-m-8', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-9', name: 'Kevin Kid', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Puck', description: 'Youthful, energetic American teen.', avatarUrl: getAvatar('us-m-9', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-10', name: 'Brian Business', gender: 'Male', category: ArtistCategory.Professional, baseVoice: 'Puck', description: 'Corporate boardroom professional.', avatarUrl: getAvatar('us-m-10', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-11', name: 'Grandpa Ted', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Charon', description: 'Old, shaky American senior voice.', avatarUrl: getAvatar('us-m-11', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-12', name: 'Officer John', gender: 'Male', category: ArtistCategory.Authoritative, baseVoice: 'Fenrir', description: 'Commanding, law enforcement tone.', avatarUrl: getAvatar('us-m-12', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-13', name: 'Tex Ranger', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Fenrir', description: 'Southern American cowboy accent.', avatarUrl: getAvatar('us-m-13', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-14', name: 'NY Vinny', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Puck', description: 'Fast-talking New York accent.', avatarUrl: getAvatar('us-m-14', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-15', name: 'Professor X', gender: 'Male', category: ArtistCategory.Educational, baseVoice: 'Charon', description: 'Slow, clear, academic lecturer.', avatarUrl: getAvatar('us-m-15', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-16', name: 'Whisper Will', gender: 'Male', category: ArtistCategory.Whisper, baseVoice: 'Charon', description: 'Close-mic ASMR whisper.', avatarUrl: getAvatar('us-m-16', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-17', name: 'Gamer Guy', gender: 'Male', category: ArtistCategory.Energetic, baseVoice: 'Puck', description: 'Excited streamer voice.', avatarUrl: getAvatar('us-m-17', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-18', name: 'History Hank', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Fenrir', description: 'American history channel narrator.', avatarUrl: getAvatar('us-m-18', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-19', name: 'Radio Rick', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Classic FM radio DJ voice.', avatarUrl: getAvatar('us-m-19', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-20', name: 'Surfer Sean', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Puck', description: 'Laid back California accent.', avatarUrl: getAvatar('us-m-20', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-21', name: 'Detective Dan', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Noir style crime narrator.', avatarUrl: getAvatar('us-m-21', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-22', name: 'Robot Ray', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Puck', description: 'Monotone sci-fi AI.', avatarUrl: getAvatar('us-m-22', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-23', name: 'Medical Mark', gender: 'Male', category: ArtistCategory.Medical, baseVoice: 'Puck', description: 'Pharmaceutical ad voice.', avatarUrl: getAvatar('us-m-23', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-24', name: 'Podcast Paul', gender: 'Male', category: ArtistCategory.Explanatory, baseVoice: 'Fenrir', description: 'Rich, NPR-style podcast host.', avatarUrl: getAvatar('us-m-24', 'Male'), language: 'English', accent: 'American' },
  { id: 'us-m-25', name: 'Action Andy', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Fenrir', description: 'Gritty action movie promo.', avatarUrl: getAvatar('us-m-25', 'Male'), language: 'English', accent: 'American' },

  // -- FEMALE BRITISH (25) --
  { id: 'uk-f-1', name: 'Emma Watson-ish', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Intelligent, young British RP accent.', avatarUrl: getAvatar('uk-f-1', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-2', name: 'Dame Judi', gender: 'Female', category: ArtistCategory.History, baseVoice: 'Kore', description: 'Mature, highly respected British theatre voice.', avatarUrl: getAvatar('uk-f-2', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-3', name: 'BBC Sarah', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Standard British news presenter.', avatarUrl: getAvatar('uk-f-3', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-4', name: 'Cockney Kate', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'East London street accent, full of character.', avatarUrl: getAvatar('uk-f-4', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-5', name: 'Scottish Isla', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Soft Scottish highlands accent.', avatarUrl: getAvatar('uk-f-5', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-6', name: 'Lady Victoria', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Kore', description: 'Posh, upper-class British tone.', avatarUrl: getAvatar('uk-f-6', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-7', name: 'Nurse Nancy', gender: 'Female', category: ArtistCategory.Medical, baseVoice: 'Zephyr', description: 'Caring, British healthcare professional.', avatarUrl: getAvatar('uk-f-7', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-8', name: 'Teacher Tuppence', gender: 'Female', category: ArtistCategory.Educational, baseVoice: 'Kore', description: 'Clear British primary school teacher.', avatarUrl: getAvatar('uk-f-8', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-9', name: 'Whispering Willow', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Zephyr', description: 'British accent ASMR whisper.', avatarUrl: getAvatar('uk-f-9', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-10', name: 'Fantasy Fay', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Ethereal British fantasy narrator.', avatarUrl: getAvatar('uk-f-10', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-11', name: 'Tech Tilly', gender: 'Female', category: ArtistCategory.Explanatory, baseVoice: 'Kore', description: 'Modern, crisp British tech reviewer.', avatarUrl: getAvatar('uk-f-11', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-12', name: 'Calm Clara', gender: 'Female', category: ArtistCategory.Calm, baseVoice: 'Zephyr', description: 'British mindfulness guide.', avatarUrl: getAvatar('uk-f-12', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-13', name: 'Energetic Ellie', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Bright British vlogger.', avatarUrl: getAvatar('uk-f-13', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-14', name: 'Promo Pippa', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Kore', description: 'Persuasive British commercial voice.', avatarUrl: getAvatar('uk-f-14', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-15', name: 'Mystery Molly', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'Hushed, British mystery narrator.', avatarUrl: getAvatar('uk-f-15', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-16', name: 'Queen Q', gender: 'Female', category: ArtistCategory.Authoritative, baseVoice: 'Kore', description: 'Royal, commanding British tone.', avatarUrl: getAvatar('uk-f-16', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-17', name: 'Irish Siobhan', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Lyrical Irish accent (British Isles).', avatarUrl: getAvatar('uk-f-17', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-18', name: 'Welsh Gwen', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'Musical Welsh accent.', avatarUrl: getAvatar('uk-f-18', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-19', name: 'Historical Harriet', gender: 'Female', category: ArtistCategory.HistoricalNarrator, baseVoice: 'Kore', description: 'British period drama narrator.', avatarUrl: getAvatar('uk-f-19', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-20', name: 'News Nora', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Urgent British news reporter.', avatarUrl: getAvatar('uk-f-20', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-21', name: 'Poet Penelope', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Rhythmic, poetic British reading.', avatarUrl: getAvatar('uk-f-21', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-22', name: 'Gamer Gem', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Excited British streamer.', avatarUrl: getAvatar('uk-f-22', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-23', name: 'Corporate Chloe', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Kore', description: 'Efficient British office voice.', avatarUrl: getAvatar('uk-f-23', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-24', name: 'Travel Tara', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Zephyr', description: 'Inviting British travel guide.', avatarUrl: getAvatar('uk-f-24', 'Female'), language: 'English', accent: 'British' },
  { id: 'uk-f-25', name: 'Audiobook Alice', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Classic British fiction narrator.', avatarUrl: getAvatar('uk-f-25', 'Female'), language: 'English', accent: 'British' },

  // -- FEMALE AMERICAN (25) --
  { id: 'us-f-1', name: 'Jennifer Aniston-ish', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Kore', description: 'Friendly, recognizable American girl-next-door.', avatarUrl: getAvatar('us-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-2', name: 'Valley Val', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'California valley girl accent.', avatarUrl: getAvatar('us-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-3', name: 'News Nancy', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Trustworthy American broadcast journalist.', avatarUrl: getAvatar('us-f-3', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-4', name: 'Mom Mary', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Warm, comforting American mother tone.', avatarUrl: getAvatar('us-f-4', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-5', name: 'Corporate Carol', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Kore', description: 'Sharp, American business executive.', avatarUrl: getAvatar('us-f-5', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-6', name: 'Fitness Fiona', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'High energy American workout coach.', avatarUrl: getAvatar('us-f-6', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-7', name: 'Southern Sue', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'Sweet Southern Belle accent.', avatarUrl: getAvatar('us-f-7', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-8', name: 'Dr. Debra', gender: 'Female', category: ArtistCategory.Medical, baseVoice: 'Kore', description: 'Professional American medical expert.', avatarUrl: getAvatar('us-f-8', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-9', name: 'Siri Style', gender: 'Female', category: ArtistCategory.Explanatory, baseVoice: 'Kore', description: 'Robotic but helpful assistant voice.', avatarUrl: getAvatar('us-f-9', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-10', name: 'Teacher Teresa', gender: 'Female', category: ArtistCategory.Educational, baseVoice: 'Kore', description: 'Patient American elementary teacher.', avatarUrl: getAvatar('us-f-10', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-11', name: 'ASMR Amber', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Zephyr', description: 'Tingly American whisper.', avatarUrl: getAvatar('us-f-11', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-12', name: 'Dramatic Dana', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Intense American thriller narrator.', avatarUrl: getAvatar('us-f-12', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-13', name: 'Podcast Paige', gender: 'Female', category: ArtistCategory.Explanatory, baseVoice: 'Zephyr', description: 'Conversational American host.', avatarUrl: getAvatar('us-f-13', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-14', name: 'Reality Rita', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Loud, dramatic reality TV voice.', avatarUrl: getAvatar('us-f-14', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-15', name: 'Grandma Grace', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Shaky, sweet elderly American.', avatarUrl: getAvatar('us-f-15', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-16', name: 'Promo Pam', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Kore', description: 'Standard American radio ad voice.', avatarUrl: getAvatar('us-f-16', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-17', name: 'Meditate Meg', gender: 'Female', category: ArtistCategory.Calm, baseVoice: 'Zephyr', description: 'Yoga instructor style.', avatarUrl: getAvatar('us-f-17', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-18', name: 'Agent Scully', gender: 'Female', category: ArtistCategory.Authoritative, baseVoice: 'Kore', description: 'Skeptical, professional investigator.', avatarUrl: getAvatar('us-f-18', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-19', name: 'Tech Tina', gender: 'Female', category: ArtistCategory.Explanatory, baseVoice: 'Kore', description: 'Silicon Valley tech presenter.', avatarUrl: getAvatar('us-f-19', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-20', name: 'Noir Nora', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'Smoky, jazz club singer vibe.', avatarUrl: getAvatar('us-f-20', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-21', name: 'History Hannah', gender: 'Female', category: ArtistCategory.History, baseVoice: 'Kore', description: 'American academic historian.', avatarUrl: getAvatar('us-f-21', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-22', name: 'Teen Taylor', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Zephyr', description: 'High school student voice.', avatarUrl: getAvatar('us-f-22', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-23', name: 'Customer Service', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Kore', description: 'Polite, automated phone system.', avatarUrl: getAvatar('us-f-23', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-24', name: 'Storytime Stacey', gender: 'Female', category: ArtistCategory.Educational, baseVoice: 'Zephyr', description: 'Librarian reading to kids.', avatarUrl: getAvatar('us-f-24', 'Female'), language: 'English', accent: 'American' },
  { id: 'us-f-25', name: 'Influencer Izzy', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Kore', description: 'Social media hype girl.', avatarUrl: getAvatar('us-f-25', 'Female'), language: 'English', accent: 'American' },

  // --- SPANISH SPECIALISTS (New 40 Artists) ---
  // Spanish Male (20) - Ensuring only Puck, Charon, Fenrir
  { id: 'sp-m-1', name: 'Mateo', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Rich Castilian accent, perfect for novels.', avatarUrl: getAvatar('sp-m-1', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-2', name: 'Santiago', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Clear, neutral Latin American broadcast tone.', avatarUrl: getAvatar('sp-m-2', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-3', name: 'Alejandro', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'Upbeat Mexican commercial voice.', avatarUrl: getAvatar('sp-m-3', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-4', name: 'Diego', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Deep, soothing, meditative Spanish.', avatarUrl: getAvatar('sp-m-4', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-5', name: 'Leonardo', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Fenrir', description: 'Serious, documentary style narration.', avatarUrl: getAvatar('sp-m-5', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-6', name: 'Carlos', gender: 'Male', category: ArtistCategory.Educational, baseVoice: 'Charon', description: 'Corporate training specialist.', avatarUrl: getAvatar('sp-m-6', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-7', name: 'Javier', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Warm, grandfatherly storyteller.', avatarUrl: getAvatar('sp-m-7', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-8', name: 'Manuel', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Rapid-fire sports commentator style.', avatarUrl: getAvatar('sp-m-8', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-9', name: 'Gabriel', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Charon', description: 'Raspy, dramatic villain voice.', avatarUrl: getAvatar('sp-m-9', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-10', name: 'Fernando', gender: 'Male', category: ArtistCategory.Explanatory, baseVoice: 'Fenrir', description: 'Smooth, tech-savvy explainer.', avatarUrl: getAvatar('sp-m-10', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-11', name: 'Ricardo', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'High energy promo voice.', avatarUrl: getAvatar('sp-m-11', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-12', name: 'Jorge', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Fenrir', description: 'Classic, old-school narrator.', avatarUrl: getAvatar('sp-m-12', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-13', name: 'Luis', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Soft spoken, therapeutic.', avatarUrl: getAvatar('sp-m-13', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-14', name: 'Miguel', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Adventure and fantasy focused.', avatarUrl: getAvatar('sp-m-14', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-15', name: 'Jose', gender: 'Male', category: ArtistCategory.Professional, baseVoice: 'Puck', description: 'Trustworthy financial advisor tone.', avatarUrl: getAvatar('sp-m-15', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-16', name: 'Antonio', gender: 'Male', category: ArtistCategory.News, baseVoice: 'Puck', description: 'Breaking news urgency.', avatarUrl: getAvatar('sp-m-16', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-17', name: 'Francisco', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Charon', description: 'Theatrical and bold.', avatarUrl: getAvatar('sp-m-17', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-18', name: 'David', gender: 'Male', category: ArtistCategory.Energetic, baseVoice: 'Puck', description: 'Youthful, modern, and cool.', avatarUrl: getAvatar('sp-m-18', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-19', name: 'Daniel', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Fenrir', description: 'Deep relaxation specialist.', avatarUrl: getAvatar('sp-m-19', 'Male'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-m-20', name: 'Pablo', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Puck', description: 'Engaging, friendly neighbor.', avatarUrl: getAvatar('sp-m-20', 'Male'), language: 'Spanish', accent: 'Global' },

  // Spanish Female (20) - Ensuring only Kore, Zephyr
  { id: 'sp-f-1', name: 'Sofia', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Warm, lyrical Spanish narration.', avatarUrl: getAvatar('sp-f-1', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-2', name: 'Valentina', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Sharp, articulate news anchor.', avatarUrl: getAvatar('sp-f-2', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-3', name: 'Isabella', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Kore', description: 'Bright, happy commercial voice.', avatarUrl: getAvatar('sp-f-3', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-4', name: 'Camila', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Zephyr', description: 'Soothing, whisper-like ASMR.', avatarUrl: getAvatar('sp-f-4', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-5', name: 'Lucia', gender: 'Female', category: ArtistCategory.Educational, baseVoice: 'Kore', description: 'Intelligent, educational tone.', avatarUrl: getAvatar('sp-f-5', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-6', name: 'Mariana', gender: 'Female', category: ArtistCategory.History, baseVoice: 'Kore', description: 'Elegant, historical recounting.', avatarUrl: getAvatar('sp-f-6', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-7', name: 'Gabriela', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Animated character storyteller.', avatarUrl: getAvatar('sp-f-7', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-8', name: 'Elena', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Zephyr', description: 'Corporate, bilingual feel.', avatarUrl: getAvatar('sp-f-8', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-9', name: 'Victoria', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Serious investigative reporter.', avatarUrl: getAvatar('sp-f-9', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-10', name: 'Martina', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Fun, party vibe.', avatarUrl: getAvatar('sp-f-10', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-11', name: 'Catalina', gender: 'Female', category: ArtistCategory.Medical, baseVoice: 'Zephyr', description: 'Calm, doctor-like persona.', avatarUrl: getAvatar('sp-f-11', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-12', name: 'Fernanda', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Kore', description: 'Sassy, dramatic roles.', avatarUrl: getAvatar('sp-f-12', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-13', name: 'Daniela', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Soft, bedtime stories.', avatarUrl: getAvatar('sp-f-13', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-14', name: 'Valeria', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Kore', description: 'Customer service excellence.', avatarUrl: getAvatar('sp-f-14', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-15', name: 'Ximena', gender: 'Female', category: ArtistCategory.Announcer, baseVoice: 'Kore', description: 'Morning show host.', avatarUrl: getAvatar('sp-f-15', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-16', name: 'Sara', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Teenager, enthusiastic.', avatarUrl: getAvatar('sp-f-16', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-17', name: 'Natalia', gender: 'Female', category: ArtistCategory.History, baseVoice: 'Kore', description: 'Museum guide voice.', avatarUrl: getAvatar('sp-f-17', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-18', name: 'Mia', gender: 'Female', category: ArtistCategory.Calm, baseVoice: 'Kore', description: 'Nature documentary style.', avatarUrl: getAvatar('sp-f-18', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-19', name: 'Paula', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Kore', description: 'Witchy or mysterious.', avatarUrl: getAvatar('sp-f-19', 'Female'), language: 'Spanish', accent: 'Global' },
  { id: 'sp-f-20', name: 'Julieta', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Romantic novel narrator.', avatarUrl: getAvatar('sp-f-20', 'Female'), language: 'Spanish', accent: 'Global' },

  // --- EXISTING LIBRARY (Updated with language: 'English' and Accent: 'American') ---
  { id: 'st-m-1', name: 'Arthur Penhaligon', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Deep, resonant, epic narrator.', avatarUrl: getAvatar('st-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'st-m-2', name: 'Grandpa Joe', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Charon', description: 'Warm, raspy, nostalgic.', avatarUrl: getAvatar('st-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'st-m-3', name: 'Leo Tales', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Puck', description: 'Playful, engaging for kids.', avatarUrl: getAvatar('st-m-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'st-m-4', name: 'Sebastian Night', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Mystery and thriller specialist.', avatarUrl: getAvatar('st-m-4', 'Male'), language: 'English', accent: 'American' },
  { id: 'st-m-5', name: 'Bard William', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Charon', description: 'Poetic and rhythmic.', avatarUrl: getAvatar('st-m-5', 'Male'), language: 'English', accent: 'American' },
  { id: 'st-f-1', name: 'Elena Story', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Soft, motherly, bedtime stories.', avatarUrl: getAvatar('st-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'st-f-2', name: 'Sarah Fable', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Zephyr', description: 'Bright, fantasy adventure.', avatarUrl: getAvatar('st-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'st-f-3', name: 'Madame Rose', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Mature, slightly husky, noir.', avatarUrl: getAvatar('st-f-3', 'Female'), language: 'English', accent: 'American' },
  { id: 'st-f-4', name: 'Fairy Luna', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Ethereal, high-pitched, magical.', avatarUrl: getAvatar('st-f-4', 'Female'), language: 'English', accent: 'American' },
  { id: 'nw-m-1', name: 'Walter Cronkite-ish', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Fenrir', description: 'Authoritative, trustworthy anchor.', avatarUrl: getAvatar('nw-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'nw-m-2', name: 'Breaking Brad', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Fast-paced, urgent, energetic.', avatarUrl: getAvatar('nw-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'nw-m-3', name: 'Global Tom', gender: 'Male', category: ArtistCategory.News, baseVoice: 'Fenrir', description: 'Neutral, international accent.', avatarUrl: getAvatar('nw-m-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'nw-m-4', name: 'Tech Marcus', gender: 'Male', category: ArtistCategory.News, baseVoice: 'Puck', description: 'Sharp, modern, articulate.', avatarUrl: getAvatar('nw-m-4', 'Male'), language: 'English', accent: 'American' },
  { id: 'nw-f-1', name: 'Barbara View', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Classic prime-time anchor.', avatarUrl: getAvatar('nw-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'nw-f-2', name: 'Daily Dana', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Morning show energy, friendly.', avatarUrl: getAvatar('nw-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'nw-f-3', name: 'Report Rachel', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Serious, investigative.', avatarUrl: getAvatar('nw-f-3', 'Female'), language: 'English', accent: 'American' },
  { id: 'nw-f-4', name: 'Weather Wendy', gender: 'Female', category: ArtistCategory.News, baseVoice: 'Kore', description: 'Bright, clear, uplifting.', avatarUrl: getAvatar('nw-f-4', 'Female'), language: 'English', accent: 'American' },
  { id: 'hs-m-1', name: 'Professor Time', gender: 'Male', category: ArtistCategory.Educational, baseVoice: 'Charon', description: 'Academic, slow, articulate.', avatarUrl: getAvatar('hs-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'hs-m-2', name: 'Ancient Al', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Fenrir', description: 'Gravelly, intense, dramatic.', avatarUrl: getAvatar('hs-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'hs-m-3', name: 'Documentary Dan', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Charon', description: 'Observational, detached.', avatarUrl: getAvatar('hs-m-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'hs-f-1', name: 'Museum Mary', gender: 'Female', category: ArtistCategory.History, baseVoice: 'Kore', description: 'Educational, precise, clear.', avatarUrl: getAvatar('hs-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'hs-f-2', name: 'Vintage Victoria', gender: 'Female', category: ArtistCategory.History, baseVoice: 'Kore', description: 'Elegant, old-world charm.', avatarUrl: getAvatar('hs-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'cm-m-1', name: 'Zen Zachary', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Deep, soothing, hypnotic.', avatarUrl: getAvatar('cm-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'cm-m-2', name: 'Sleepy Sam', gender: 'Male', category: ArtistCategory.Calm, baseVoice: 'Charon', description: 'Soft, whisper-adjacent, slow.', avatarUrl: getAvatar('cm-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'cm-f-1', name: 'Serenity Sue', gender: 'Female', category: ArtistCategory.Calm, baseVoice: 'Zephyr', description: 'Gentle, guided meditation.', avatarUrl: getAvatar('cm-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'cm-f-2', name: 'Nature Nancy', gender: 'Female', category: ArtistCategory.Calm, baseVoice: 'Kore', description: 'Earthy, grounded, reassuring.', avatarUrl: getAvatar('cm-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'cm-f-3', name: 'Breathe Bella', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Kore', description: 'Breathy, incredibly soft.', avatarUrl: getAvatar('cm-f-3', 'Female'), language: 'English', accent: 'American' },
  { id: 'en-m-1', name: 'Hype Harry', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'Over-the-top, radio DJ style.', avatarUrl: getAvatar('en-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'en-m-2', name: 'Sales Steve', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Puck', description: 'Persuasive, punchy, loud.', avatarUrl: getAvatar('en-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'en-f-1', name: 'Promo Patty', gender: 'Female', category: ArtistCategory.Promotional, baseVoice: 'Zephyr', description: 'Upbeat, fast, exciting.', avatarUrl: getAvatar('en-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'en-f-2', name: 'Action Alice', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Dynamic, trailer voice.', avatarUrl: getAvatar('en-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'pr-m-1', name: 'Corporate Carl', gender: 'Male', category: ArtistCategory.Professional, baseVoice: 'Puck', description: 'Clean, neutral, training videos.', avatarUrl: getAvatar('pr-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'pr-m-2', name: 'Explainer Eric', gender: 'Male', category: ArtistCategory.Explanatory, baseVoice: 'Puck', description: 'Friendly, helpful, clear.', avatarUrl: getAvatar('pr-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'pr-f-1', name: 'Training Tina', gender: 'Female', category: ArtistCategory.Educational, baseVoice: 'Kore', description: 'Clear, paced, articulate.', avatarUrl: getAvatar('pr-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'pr-f-2', name: 'Support Sarah', gender: 'Female', category: ArtistCategory.Professional, baseVoice: 'Zephyr', description: 'Empathetic, polite, service.', avatarUrl: getAvatar('pr-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'ch-m-1', name: 'Pirate Pete', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Fenrir', description: 'Gruff, aggressive, slurred.', avatarUrl: getAvatar('ch-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'ch-m-2', name: 'Robot Rob', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Fenrir', description: 'Monotone, clipped, metallic.', avatarUrl: getAvatar('ch-m-2', 'Male'), language: 'English', accent: 'American' },
  { id: 'ch-m-3', name: 'Wizard Will', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Charon', description: 'Old, wise, crackly.', avatarUrl: getAvatar('ch-m-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'ch-f-1', name: 'Witch Wendy', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Kore', description: 'Cackling, sharp, wicked.', avatarUrl: getAvatar('ch-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'ch-f-2', name: 'Android Anna', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Kore', description: 'Cold, precise, emotionless.', avatarUrl: getAvatar('ch-f-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'as-m-1', name: 'Close Mike', gender: 'Male', category: ArtistCategory.Whisper, baseVoice: 'Charon', description: 'Intimate, textured whisper.', avatarUrl: getAvatar('as-m-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'as-f-1', name: 'Soft Sophie', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Zephyr', description: 'Tingles, very soft, slow.', avatarUrl: getAvatar('as-f-1', 'Female'), language: 'English', accent: 'American' },
  { id: 'fl-1', name: 'Marcus Aurelius', gender: 'Male', category: ArtistCategory.History, baseVoice: 'Charon', description: 'Philosophical and stoic.', avatarUrl: getAvatar('fl-1', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-2', name: 'Jenny Pop', gender: 'Female', category: ArtistCategory.Energetic, baseVoice: 'Kore', description: 'Bubblegum pop energy.', avatarUrl: getAvatar('fl-2', 'Female'), language: 'English', accent: 'American' },
  { id: 'fl-3', name: 'Dark Noir', gender: 'Male', category: ArtistCategory.Storytelling, baseVoice: 'Fenrir', description: 'Gritty detective monologue.', avatarUrl: getAvatar('fl-3', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-4', name: 'News Flash', gender: 'Male', category: ArtistCategory.Announcer, baseVoice: 'Puck', description: 'Rapid fire updates.', avatarUrl: getAvatar('fl-4', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-5', name: 'Calm River', gender: 'Female', category: ArtistCategory.Calm, baseVoice: 'Zephyr', description: 'Like a flowing stream.', avatarUrl: getAvatar('fl-5', 'Female'), language: 'English', accent: 'American' },
  { id: 'fl-6', name: 'Dr. Science', gender: 'Male', category: ArtistCategory.Medical, baseVoice: 'Puck', description: 'Analytical, sterile, and precise.', avatarUrl: getAvatar('fl-6', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-7', name: 'Mrs. Doubt', gender: 'Female', category: ArtistCategory.Character, baseVoice: 'Kore', description: 'Wobbly elderly lady.', avatarUrl: getAvatar('fl-7', 'Female'), language: 'English', accent: 'American' },
  { id: 'fl-8', name: 'Coach Carter', gender: 'Male', category: ArtistCategory.Promotional, baseVoice: 'Fenrir', description: 'Motivational and loud.', avatarUrl: getAvatar('fl-8', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-9', name: 'Library Linda', gender: 'Female', category: ArtistCategory.Whisper, baseVoice: 'Zephyr', description: 'Shushing, quiet, polite.', avatarUrl: getAvatar('fl-9', 'Female'), language: 'English', accent: 'American' },
  { id: 'fl-10', name: 'Commander X', gender: 'Male', category: ArtistCategory.Character, baseVoice: 'Fenrir', description: 'Sci-fi military leader.', avatarUrl: getAvatar('fl-10', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-11', name: 'Tech Support', gender: 'Male', category: ArtistCategory.Explanatory, baseVoice: 'Puck', description: 'Patient, slow explanations.', avatarUrl: getAvatar('fl-11', 'Male'), language: 'English', accent: 'American' },
  { id: 'fl-12', name: 'Fairy Godmother', gender: 'Female', category: ArtistCategory.Storytelling, baseVoice: 'Kore', description: 'Granting wishes tone.', avatarUrl: getAvatar('fl-12', 'Female'), language: 'English', accent: 'American' },
];

export const CATEGORIES = Object.values(ArtistCategory);
export const EMOTIONS = Object.values(Emotion);
